/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module addValue_8 (
    input [15:0] sequenceCount,
    output reg [15:0] addvalue
  );
  
  
  
  always @* begin
    
    case (sequenceCount)
      16'h0001: begin
        addvalue = 16'h0001;
      end
      16'h0002: begin
        addvalue = 16'h0002;
      end
      16'h0003: begin
        addvalue = 16'h0004;
      end
      16'h0004: begin
        addvalue = 16'h0008;
      end
      16'h0005: begin
        addvalue = 16'h0010;
      end
      16'h0006: begin
        addvalue = 16'h0020;
      end
      16'h0007: begin
        addvalue = 16'h0040;
      end
      16'h0008: begin
        addvalue = 16'h0080;
      end
      16'h0009: begin
        addvalue = 16'h0100;
      end
      16'h000a: begin
        addvalue = 16'h0200;
      end
      16'h000b: begin
        addvalue = 16'h0400;
      end
      16'h000c: begin
        addvalue = 16'h0800;
      end
      16'h000d: begin
        addvalue = 16'h1000;
      end
      16'h000e: begin
        addvalue = 16'h2000;
      end
      16'h000f: begin
        addvalue = 16'h4000;
      end
      16'h0010: begin
        addvalue = 16'h8000;
      end
      default: begin
        addvalue = 16'h0000;
      end
    endcase
  end
endmodule
